-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
--
-- Autocmd buat ngerapiin file Hyprland otomatis pas save
-- vim.api.nvim_create_autocmd("BufWritePre", {
--  pattern = { "*.conf", "*.hypr" }, -- Cuma jalan di file config/hyprland
--  callback = function()
--    local view = vim.fn.winsaveview() -- Simpan posisi kursor biar gak loncat
--    vim.cmd("normal! gg=G") -- Jalanin jurus rapi-rapi
--    vim.fn.winrestview(view) -- Balikin kursor ke tempat asal
--  end,
--})
