# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua


$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
# for cursor
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

cursor {
    no_hardware_cursors = false
}

general {
    gaps_in = 2
    gaps_out = 0
    border_size = 1
    col.active_border = rgba(89b4faff) rgba(cba6f7ff) 90deg
    col.inactive_border = rgba(313244ff)
}

decoration {
    rounding = 10
}


workspace = w[tv1], gapsout:0, gapsin:0, bordersize:0
workspace = f[1], gapsout:0, gapsin:0, bordersize:0

monitor=,1920x1080@60.00500,auto,1



bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, L, exec, hyprlock
bind = SUPER, F,       fullscreen, 0
bind = SUPER SHIFT, F, fullscreen, 1
bind = SUPER, B, exec, pkill waybar || waybar &
bind = $mainMod SHIFT, R, exec, killall -9 waybar; waybar

# keyboard resizing
bind = SUPER ALT, left,  resizeactive, -30 0
bind = SUPER ALT, right, resizeactive,  30 0
bind = SUPER ALT, up,    resizeactive,  0 -30
bind = SUPER ALT, down,  resizeactive,  0  30

# moving window
bind = SUPER SHIFT, left,  movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up,    movewindow, u
bind = SUPER SHIFT, down,  movewindow, d

# switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = CTRL SUPER, right, workspace, +1
bind = CTRL SUPER, left,  workspace, -1

# switch musics
bind = SUPER SHIFT, n, exec, playerctl next
bind = SUPER SHIFT, b, exec, playerctl previous
bind = SUPER SHIFT, p, exec, playerctl play-pause

# mouse:272 = left click → move window | mouse:273 = right click → drag to resize
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow



exec-once = awww-daemon
exec-once = waybar
exec-once = swaync

# applay Dark theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Andromeda-dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Flat-Remix-Blue-Dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface font-name 'Open Sans 11'
# cursor 
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24


binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binde = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
binde = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bind = ,XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-


