general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

background {
    path = $HOME/.config/wallpapers/wallhaven-e88r8o_1920x1080.png
    blur_passes = 0
    contrast = 1
    brightness = 0
    vibrancy = 0
}

input-field {
    size = 500, 80
    rounding = 0
    dots_size = 0.1
    dots_spacing = 0.5
    radius = 10px
    outline_thickness = 1
    outer_color = rgba(40, 40, 255, 255)
    inner_color = rgba(255, 0, 0, 255)
    font_color = rgb(ffffff)
    check-text =
    placeholder_text = <i><span foreground="##050506">...</span></i>
}

# TIME LABEL
label {
    monitor =
    text = $TIME
    font_size = 100
    font_family = SpaceMono Nerd Font bold
    font_weight = 900
    color = rgba(255, 255, 255, 0.8)

    position = 0, -100
    halign = center
    valign = top
}

# USER LABEL
label {
    monitor =
    text = $USER
    font_size = 24
    font_family = 0xProto Nerd Font bold
    color = rgba(255, 255, 255, 0.8)

    position = 0, -280
    halign = center
    valign = top

}

# COUTS LABEL
label {
    monitor =
    text = `Look at me! Look at me!,The monster inside of me has gotten this big!`
    font_size = 8
    font_family = 0xProto Nerd Font bold
    color = rgba(255, 255, 255, 0.8)

    position = 0, -330
    halign = center
    valign = top
}

# Spotify Status with Icon`
label {
    monitor =
    text=cmd[update:2000] $HOME/.config/scripts/spotify_status.sh
    font_size = 16
    font_family = 0xProto Nerd Font
    color = rgb(30, 215, 96)

    position = 0, 25
    halign = center
    valign = bottom
}

# Battery Status (Bottom-Right)
label {
    monitor =
    # Fetches percentage and sets an icon depending on charging state
    text = cmd[update:5000] echo "$(cat /sys/class/power_supply/BAT0/status) $(cat /sys/class/power_supply/BAT0/capacity)%"
    font_size = 12
    font_family = 0xProto Nerd Font
    color = rgba(255, 255, 255, 0.7)

    position = -25, 25
    halign = right
    valign = bottom
}

